"""用你重新标注的图（relabel_done/ + relabel/ 里"人工存过"的）打包成 YOLO 训练集。

只收"人工标注过"的图：标签 .txt 修改时间晚于图片(>60s) 且 非空。
→ 你跳过的重复/模糊图（没存过、保留旧自动标签）全部自动排除。

可选：把 data/training/photo/背景图/ 作为空标签负样本加入，压低误检。

输出：data/training/yolo_dataset/{images,labels}/{train,val,test} + data.yaml
data.yaml 的类名用 class_map.json 的英文 key（和现有 GUI 翻译链一致；标签本身是编号，与显示语言无关）。

用法：  python scripts/prepare_relabel.py
然后：  python scripts/train_yolo.py
"""
import json
import random
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRAIN = ROOT / "data" / "training"
# 自动发现所有 relabel* 批次文件夹（relabel/relabel_done/relabel2/relabel3/...），
# 新建批次无需再改这里。按名排序，dedup 取第一个，含标签的优先。
SOURCES = sorted(p for p in TRAIN.glob("relabel*")
                 if p.is_dir() and (p / "images").is_dir())
OUT = TRAIN / "yolo_dataset"
BG_DIR = TRAIN / "photo" / "背景图"
SPLIT = (0.7, 0.2, 0.1)
MARGIN = 60.0
ADD_BACKGROUND = True
EXT = (".jpg", ".jpeg", ".png", ".bmp")
random.seed(42)


def user_labeled(img, lbl_dir):
    """这张图是不是"人工标注过"：标签晚于图片 >60s 且非空。"""
    t = lbl_dir / f"{img.stem}.txt"
    if not t.exists():
        return False
    if not t.read_text(encoding="utf-8").strip():
        return False
    return t.stat().st_mtime > img.stat().st_mtime + MARGIN


def main():
    classes = list(json.load(
        open(ROOT / "data" / "yolo" / "class_map.json", encoding="utf-8")).keys())

    pairs, seen = [], set()
    per_src = {}
    for src in SOURCES:
        imgdir, lbldir = src / "images", src / "labels"
        if not imgdir.is_dir():
            continue
        cnt = 0
        for img in sorted(imgdir.iterdir()):
            if img.suffix.lower() not in EXT or img.stem in seen:
                continue
            if user_labeled(img, lbldir):
                seen.add(img.stem)
                pairs.append((img, lbldir / f"{img.stem}.txt"))
                cnt += 1
        per_src[src.name] = cnt

    bg = 0
    if ADD_BACKGROUND and BG_DIR.is_dir():
        for img in sorted(BG_DIR.iterdir()):
            if img.suffix.lower() in EXT:
                pairs.append((img, None))   # 空标签负样本
                bg += 1

    print(f"类别({len(classes)}): {classes}")
    for s, c in per_src.items():
        print(f"  来自 {s}: {c} 张人工标注")
    if bg:
        print(f"  背景负样本: {bg} 张")
    print(f"合计有效图: {len(pairs)}")
    if not pairs:
        raise RuntimeError("没有任何人工标注图，检查 relabel_done/")

    random.shuffle(pairs)
    n = len(pairs)
    n_tr, n_va = int(n * SPLIT[0]), int(n * SPLIT[1])
    splits = {"train": pairs[:n_tr], "val": pairs[n_tr:n_tr + n_va],
              "test": pairs[n_tr + n_va:]}

    if OUT.exists():
        shutil.rmtree(OUT)
    for s, items in splits.items():
        (OUT / "images" / s).mkdir(parents=True, exist_ok=True)
        (OUT / "labels" / s).mkdir(parents=True, exist_ok=True)
        for img, lbl in items:
            shutil.copy(img, OUT / "images" / s / img.name)
            dst = OUT / "labels" / s / f"{img.stem}.txt"
            if lbl is not None:
                shutil.copy(lbl, dst)
            else:
                dst.write_text("", encoding="utf-8")
        print(f"  {s}: {len(items)} 张")

    (OUT / "data.yaml").write_text(
        "# Generated by scripts/prepare_relabel.py（只用重新标注的图）\n"
        f"path: {OUT.resolve().as_posix()}\n"
        "train: images/train\nval: images/val\ntest: images/test\n\n"
        f"nc: {len(classes)}\nnames: {classes}\n",
        encoding="utf-8")
    print(f"\n✅ data.yaml 已生成: {OUT / 'data.yaml'}")
    print("   下一步: python scripts/train_yolo.py")


if __name__ == "__main__":
    main()
